export const GET_ACCUMULATORS = 'GET_ACCUMULATORS';
export const GET_ACCUMULATORSBYBRAND = 'GET_ACCUMULATORSBYBRAND';
export const GET_ACCUMULATOR = 'GET_ACCUMULATOR';
export const SET_LOADING = 'SET_LOADING';
export const GET_TIRES = 'GET_TIRES';
export const GET_TIRE = 'GET_TIRE';
export const GET_ACCESSORIES = 'GET_ACCESSORIES';
export const GET_ACCESSORY = 'GET_ACCESSORY';