export const GET_ACCUMULATORS = 'GET_ACCUMULATORS';
export const GET_ACCUMULATORSBYBRAND = 'GET_ACCUMULATORSBYBRAND';
export const GET_ACCUMULATOR = 'GET_ACCUMULATOR';
export const SET_LOADING = 'SET_LOADING';